import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  clientSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // clientSidebar: [
  //     'client/intro',
  //     {
  //         type: 'category',
  //         label: 'IvyNet Client',
  //         items: ['client/ClientExplanation', 'client/create-a-blog-post', 'client/create-a-document', 'client/create-a-page', 'client/deploy-your-site', 'client/markdown-features', 'client/zzcongratulations'],
  //     },
  // ],
};

export default sidebars;
